all: 01_ordinary_pipe 02_named_pipe_2 02_named_pipe_1

01_ordinary_pipe: 01_ordinary_pipe.cpp
	g++ -o 01_ordinary_pipe 01_ordinary_pipe.cpp

02_named_pipe_1: 02_named_pipe_1.cpp
	g++ -o 02_named_pipe_1 02_named_pipe_1.cpp

02_named_pipe_2: 02_named_pipe_2.cpp
	g++ -o 02_named_pipe_2 02_named_pipe_2.cpp