all: 01_smem_producer

01_smem_producer: 01_smem_producer.cpp
	g++ -o 01_smem_producer 01_smem_producer.cpp -lrt

01_smem_consumer: 01_smem_consumer.cpp
	g++ -o 01_smem_consumer 01_smem_consumer.cpp -lrt
